### ISSUE TITLE
Meeting 12th April 2021

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/CROP#101]
**Date**: 10AM 12th April 2021 

**Attendees**:
 1. Rebecca W 
 2. Melanie J-S 
 3. May Y
 4. Tomas L 	

**Agenda**

1. Funding for Crop app
2. Energy data ingestion
3. Adding models via virtual machine
4. Preparing models to be imbedded in digital twin
5. Using model outputs
6. Conference paper
7. May to meet team, and get overview of project goals and status

**Summary**

My understanding is as follows: 

1. Rebecca has two models, one in R and the other in Python. We would like to enable interaction of these models with the CROP web-app. There is additional complexity in that the models are retrained regularly. 
**Action**: May will contact Rebecca to set a date to talk about models. 
**Output**: A couple of paragraphs listing the purpose, inputs and outputs of models. 

2. There are currently problems with the web-app, possibly linked to  ##100. We should make a list of all issues and work our way down. Melanie has already identified and proposed some solutions. 
**Action** Flora to spin up local version, try to evaluate how long/difficult each issue will be to solve. 
**Output**: A list of known issues, proposed solutions and (very rough) evaluation of how long it would take the resolve.

3. There is a specific problem with accessing data in the current web-app. 
**Action** Tomas and May to look at this together next week?
**Output** May to be able to understand how this section works. 

3. Mel proposed a new idea for the landing page. This comprises of a dashboard that summarises the most important information. May agrees this is a good idea. 
**Action** We should arrange a time to mock up (just on pen and paper) what the most important information is.
**Output** A mock up of what information should be prioritised and shown on landing page

4. Mel has an idea about incorporating new sensor data. This can also be achieved in stages, but will require the visualisations to work the right way, and the data structures to be set up. 
**Action** May and Tomas will schedule some time to draw up architecture diagram to evaluate how this can be done.  :white_check_mark:
**Output** Architecture sketch listing the components of the web app and showing how they currently link together.

5. This team would currently like to meet weekly for the next 4 weeks (is this ok, people?) and will consider meeting fortnightly after that if tasks have become clearer.
**Action** May to schedule next week's meeting for 10 GMT 19th April 2021. :white_check_mark:

6. The team's idea of a successful project is that, in six months we should have a web-app that can be easily accessible by Growing Underground, contains a 'summary' dashboard and allows users to create 'what if' scenarios with the models.

**Comment by rmward61** [comment]
_1. Rebecca has two models, one in R and the other in Python_
Melanie has created statistical models in R that work directly on the data and forecast the future.  In addition Rebecca has a physics-based Python model that calculates the environmental conditions in the farm based on external weather conditions.  A continuous calibration process has been developed for this latter model, so that it takes in monitored data and calculates the value for two model parameters that ensure that the model matches the observed data as well as possible.  This physics-based model can then be used for scenario simulation - the ‘what if?’ questions.  We wish to embed both types of model into CROP.
