### ISSUE TITLE
Enumerate known issues with current webapp

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/CROP#102]
We want to enumerate all known issues with the master branch of the webapp.

**Template**
- [ ] Test user can't log in
Problem: Azure database not connecting
Proposed Solution: Make changes to credentials
Expected Output: Test User logs in

**Comment by entopia** [comment]
- [ ] Errors in dependencies
Problem: New releases in dependencies are not compatible. 
Proposed solution: update requirements.txt with == 
Expected output: Users should be installing the original version of the dependencies

- [ ] Local server set up
Problem:  Users are having problems setting up a local server
Proposed solution: write up step by step documentation for both mac and pc.

- [ ] Unity loading
Problem: Unity takes time to load in some users
Proposed solution: Speak with Melanie to define the issue. Seems to load ok in my version. 
Expected solution: Unity should not take longer that 30 sec to 1 min to load.

- [ ] Loading sensors error
Problem: Unity not loading sensors when running locally
Proposed solution: Update the requests (when running locally, request need to be updated)
Expected solution: There should be a function to automatically update the requests when running locally. 

- [ ] Test user can't log in
Problem: Seems that test user is not authorised to access the app locally
Proposed Solution: Make changes to credentials
Expected Output: Test User logs in
