### ISSUE TITLE
Insert weather data from pulled from API endpoint

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/CROP#108]
This issue charts progress about pulling the pulling data from Zensie/30 MHZ API and inserting them into the weather table in the croptestsqlserver database

The two issues that are relevant are:
1) Which API endpoint #106 
2) Put CSV data into database #107 

**Action:** 
- [x] To start with, we need to check if weather variables are correct. 
- [x] Then we need to insert a new sensor into the sensor table https://github.com/alan-turing-institute/CROP/issues/108#issuecomment-832086173
- [x] Then we will write the script to pull out the sensor/checkID to formulate the API 
- [x] Then receive the JSON response, and put into app_db.iweather table.

**Success criteria**
This issue can be closed when data can be pulled and inserted using new Python scripts eg. ingress_weather

**Comment by entopia** [comment]
Alternative API for weather data which is used in the Unity 3D : https://openweathermap.org/api

**Comment by myyong** [comment]
I inserted into sensor_types the following:

```SQL
INSERT INTO sensor_types
( -- columns to insert data into
 sensor_type, source, origin, frequency, data, description, time_created
)
VALUES
( -- first row: values for the columns in the list above
 '30MHz Weather', 
 '30MHz Zensie',  
 'Zensie API', 
 '60 mins', 
 'temperature,rain_probability,relative_humidity, rain, radiation, wind_speed,air_pressure,wind_direction',
 'https://api.30mhz.com/api/stats/check/i-b9bf5432-9436-11ea-b286-79ffe41fb933/from/YYYY-MM-DDTHH:MM:SSZ/until/YYYY-MM-DDTHH:MM:SSZ?statisticType=averages&intervalSize=60m',
 '2021-05-04 00:00:00.00'
)
```

and into sensors the following:
```SQL
INSERT INTO sensors
( -- columns to insert data into
 type_id, device_id, name
)
VALUES
( -- first row: values for the columns in the list above
 11, 'i-b9bf5432-9436-11ea-b286-79ffe41fb933', 'i_weathers'
)
```

This means that filtering the sensors for '30MHz Weather' sensor-types will return the following

| sensors_type_id | sensors_id |           sensors_device_id            |
| ----------- | ----------- | -----------|
| 11 |         47 | i-b9bf5432-9436-11ea-b286-79ffe41fb933   |

The SQL command used to filter is:

```SQL
SELECT sensors.type_id AS sensors_type_id, sensors.id AS sensors_id, sensors.device_id AS sensors_device_id 
FROM sensors, sensor_types 
WHERE sensor_types.sensor_type = '30MHz Weather' AND sensors.type_id = sensor_types.id
```

**Comment by myyong** [comment]
Commit d47a12d meets the criteria below:
- [x]Then we will write the script to pull out the sensor/checkID to formulate the API
- [x]Then receive the JSON response, and put into app_db.iweather table.

This can be checked by running the following from CROP:

```bash
cd .secrets/
source crop.sh
cd ..
conda activate crop
python ./__app__/crop/ingress_weather.py
psql "host=cropapptestsqlserver.postgres.database.azure.com port=5432 dbname=app_db user=<username> password=<password>
 sslmode=require"
Select * from iweather order by timestamp desc limit 3;
```
returns
| id   |   temperature    | rain_probability |       rain        | relative_humidity |    wind_speed    |  wind_direction  |   air_pressure   |    radiation     |      timestamp      | time_created | time_updated | sensor_id 
|-------|------------------|------------------|-------------------|-------------------|------------------|------------------|------------------|------------------|---------------------|--------------|--------------|-----------|
 21159 | 8.60000038146973 | 16.1000003814697 | 0.370000004768371 |  68.6999969482422 | 2.90000009536743 | 296.799987792969 | 1006.09997558594 | 264.682006835938 | 2021-05-05 17:00:00 |              |              |        47
 21158 | 9.39999961853027 | 73.8000030517578 |  1.79999995231628 |  64.6999969482422 |                4 | 304.600006103516 | 1006.09997558594 |  82.818000793457 | 2021-05-05 16:00:00 |              |              |        47
 21157 | 9.30000019073486 | 11.3000001907349 |              0.25 |  63.2999992370605 | 1.70000004768371 |            235.5 | 1006.20001220703 | 322.596008300781 | 2021-05-05 15:00:00 |              |              |        47 |

**Comment by rmward61** [comment]
Completed
