### ISSUE TITLE
Growth table

### ISSUE THREAD

**Issue by entopia** [alan-turing-institute/CROP#119]
Fields: 
e.g : 

Id:
Location: 
plant type:
growth lv:
.... ??

**Comment by meljsingh** [comment]
I was thinking two options:

(A) Simple table with manual data entries
| id | Year | TotalYield | CumulativeYield | GrowingArea|
|----|------|------------|-----------------|--------|
| 1  | 2016 | 25         | 25              |368|
| 2  | 2017 | 28         | 53              |368|
| 3  | 2018 | 30         | 83              |528|
| 4  | 2019 | 32         | 115             |528|

Or we use the latest format from the google forms used at the farm, which you will find in an email.

**Comment by meljsingh** [comment]
CREATE TABLE tableName
(
     id 	varchar(300),
     Year 	varchar(300),
     TotalYield 	varchar(300),
     CumulativeYield 	varchar(255)
);

INSERT INTO tableName ( id , Year , TotalYield , CumulativeYield )
VALUES
    ('1', '2016', '25', '25'),
    ('2', '2017', '28', '53'),
    ('3', '2018', '30', '83'),
    ('4', '2019', '32', '115');

**Comment by entopia** [comment]
There may be a need to add an other table "CROP type" (corriander, etc.. )

**Comment by entopia** [comment]
Hi @meljsingh , 

I just looked into the old tables we had integrated, and it looks like we had used this table from the google sheets you had given us: 

crop = Column(String, nullable=False)
    propagation_date = Column(DateTime, nullable=False)
    location_id = Column(
        Integer,
        ForeignKey("{}.{}".format(LOCATION_TABLE_NAME, ID_COL_NAME)),
        nullable=False,
    )
    trays = Column(Integer, nullable=False)
    m2 = Column(Float, nullable=False)
    supplier = Column(String, nullable=False)
    batch_no = Column(String, nullable=False)
    date_underlight = Column(DateTime, nullable=False)
    week_harvested = Column(DateTime, nullable=False)
    harvest_date = Column(DateTime, nullable=False)
    traceability = Column(String, nullable=False)
    surplus_waste_trays = Column(Float, nullable=False)
    est_disease_trays = Column(Float, nullable=False)
    mass_harvested = Column(Float, nullable=False)
    total_waste_p = Column(Float, nullable=False)  # percentages (?)
    surplus_waste_p = Column(Float, nullable=False)
    total_waste_m2 = Column(String, nullable=False)
    total_waste_p = Column(Float, nullable=False)
    waste_explanation = Column(String, nullable=False)  # no ref on what that is
    yield_m2 = Column(Float, nullable=False)
    propagation_days = Column(Float, nullable=False)
    days_under_lights = Column(Float, nullable=False)
    unique_code = Column(String, nullable=False)
    surplus_wasted = Column(Float, nullable=False)
    x_g = Column(Float, nullable=False)
    total_waste_g = Column(Float, nullable=False)
    projected_yeild_m = Column(Float, nullable=False)
    projected_yield_tot = Column(Float, nullable=False)
    num_trays_wasted = Column(String, nullable=True)

Shall we keep it like that?

**Comment by meljsingh** [comment]
Hi Flora, 
No I don't think it's necessary to keep the old table. Instead it ought to have either the format I sent you in the email, or the simple format described above!
