### ISSUE TITLE
webapp Image not on Dockerhub

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/CROP#130]
We tried to run the docker image from Docker Hub directly after failing to build them ourselves. We note that the `webappbase` image was [published on Docker Hub](https://hub.docker.com/u/turingcropapp) and we were able to download it. However, the `webapp` image was not on Docker Hub. We suspect it hasn't been pushed; possibly this is because the project is still in development and a fully functional webapp is not yet working. Some documentation on this might help clear up any confusion!

**Comment by mhauru** [comment]
This seems to have been fixed at some point, the image is now on Docker Hub.
