### ISSUE TITLE
Workflow for pulling updates to dynamic model

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/CROP#138]
This issue will be closed when we have process for May pulling updates to the dynamic model code.

We will be working off two branches `reproduce-dynamic-model` and `update-to-model`. When RW makes a change to `update-to-model` RW makes a pull request to merge these changes to `reproduce-dynamic-model`.  MY will be notified and accepts the merge. MY will continue to work on `reproduce-dynamic-model` while referencing the new changes.

**Comment by myyong** [comment]
1) `git clone https://github.com/alan-turing-institute/CROP.git`
2) `git checkout reproduce-dynamic-model`
3) `git checkout update-dynamic-model`

RW:
1) Makes changes to code eg (changes to RunCalibration.py)
2) `git add RunCalibration.py`
3) `git commit -m 'New parameters added'`
4) `git push`

MY:

**Comment by rmward61** [comment]
This is now not relevant - working off versioning branch
