### ISSUE TITLE
Items needing completion/fixing

### ISSUE THREAD

**Issue by rmward61** [alan-turing-institute/CROP#147]
- [x]   Fix bugs so all links work as they should.  This includes the Energy Use dashboard,  List of Sensors, Readings, Logs.

- [x] Webpage needs to scale appropriately for a smaller screen.

- [x]  Fix Unity model so links to sensors are shown and sensors can be accessed. 

- [x] Currently the unity model legend is cut off at the bottom, fix so all legend can be seen and different sensors selected.

- [x]  The alerts are great, but remove the 'read more' links or make them useful.

- [x]  Instead of having the unity model on the landing page can we have a static image of it with a link to the actual model?

- [x]   Can we give an immediate view of current temperatures/relative humidities in the tunnel? I know this can be accessed through the unity model but it would be useful to be able to see very quickly what the current temperature/RH are? 
**Main dashboard a box with average current temp and humidity from the mid farm with timestamp**

- [x]  The ARIMA prediction plot shows a mean prediction with an upper and lower bound.  Can we show the mean as a solid line with the area between the upper and lower bounds shaded?  Can we add the BSTS forecast? And can we add the monitored data for comparison (see below)?  We will need to show 4 forecasts on the page, 3 historical plus the most current which will be generated offline and uploaded to the database, so the dashboard will just need to pull the most recent sets of values.

- [x]  The prediction only shows one sensor - which one is it?  Can we show predictions for all three?
- [ ] 
- [x]  The predictions are for two days ago to the current time, not two days into the future. That's why I'm asking to plot monitored data as well.  We also need the correct timeline on the x axis - can this be pulled in with the predictions as depending on the time of day at which the forecast is generated, it will either start from 4am or 4pm.
- [x]   Clarify headline numbers - what does 'Total' mean, is it per year, per month or ever? What are 'total midnight collectors'?
- [x]  Add units where Relative Humidity is mentioned - it's in %.  Add 'C' to Temperatures so they read 23 oC (with the 'o' as a superscript?).
- [x]  Make the sensor names more meaningful in the 30MHz analysis dashboard.  So for example FARM_T/RH_16B1 should read Farm column 16, bottom tray.
- [x]   On the landing page the counts data is not intuitive and it might be because of the colours used?  I would use different colour palettes for temperature and humidity with red too hot and blue too humid. **humidity blue colorramp**
- [x]   On the landing page where does the vertical stratification data come from, is this the centre of the farm?  Give a legend that refers to the sensors?
- [x]   Add a longitudinal stratification plot underneath showing the front and the back of the farm, labelled clearly again? **sensors 1 and 29 as time series graph in the same plot**
- [x]   On the 30MHz Dashboard I find the plots difficult to read as they are so big.  Can we make this more compact (given that it needs to scale for a smaller screen)?
- [x]  What does the list of locations refer to and how does it connect to the rest of the dashboard? The list of sensors is different from the list of locations, is this correct?
- [ ] Add location to sensor page.

**Comment by rmward61** [comment]
Add
- Predictions only shown for one sensor and it isn't clear which one it is - can we have all three predictions labelled as to which sensor they are.

**Comment by rmward61** [comment]
I'm thinking the forecast plots could look something like this?

![Forecast_16B2_241121_am_future](https://user-images.githubusercontent.com/12870322/143285219-f9cd6802-c89e-47f2-9e21-53ae92453945.png)

**Comment by mhauru** [comment]
@rmward61 I've made a new issue for the one remaining tick box here: https://github.com/alan-turing-institute/CROP/issues/157 I would propose closing this issue just to clean up the list of open issues a bit, since everything else here is done. Feel free to reopen this if you'd prefer.
