### ISSUE TITLE
Clarify branch structure of the repo

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/CROP#164]
Both `develop` and `explore_dynamic_model` are substantially ahead of `master`. I'm not entirely sure what are all the things included in `explore_dynamic_model`, but `develop` has practically become the new `master` for frontend development. Maybe it would be good to merge it all to `master` and reset the baseline on which new feature branches are built?

**Comment by rmward61** [comment]
Yes, we should merge all to `master`.  The two functioning forecasting models that I'm running daily are under `explore_dynamic_model`.  By merging all to `master` would that essentially give us a frozen version of CROP 2 to start from?

**Comment by mhauru** [comment]
`develop` and `explore-dynamic-model` have been merged to master.
