### ISSUE TITLE
Re-integrate electricity consumption data when available

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/CROP#174]
I think we are waiting on someone external (from GU?) on this. @rmward61 do you know more?

**Comment by rmward61** [comment]
Yes, this is in hand at GU and we are waiting for them to let us know when the data are available again.

**Comment by mhauru** [comment]
The energy function has been on-and-off in its functioning, and is currently turned off. Reinvestigate whether we could replace the current function with one that actually queries an API, and if not, make a decision on how to restore the old version to a working state.
