### ISSUE TITLE
Consolidate Azure resources / resource groups

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/CROP#183]
Currently we have the following resource groups:
* **cropapp**: contains _cropappsqlserver_ and _cropappstorage_
* **cropapptest** contains "test" sqlserver and storage, some azure functions, and _cropapptestwebappservice_ and _cropapptest_, which I think are the actual running webapp, using the docker image `turingcropapp/webapp:cropapptest`.
* **cropmodels** contains a VM called "cropmodels", and some associated resources.
* **croptest** contains a storage account called "cropstorage", looks like it has some old sensor data from early 2020.
* Then there are a couple of other "DefaultResourceGroups", presumably for Azure monitoring.

It looks like currently the docker image `turingcropapp/webapp:cropapp` that is built by Travis upon pushes to `main`, is not being used by any webapp.

Would suggest we: 
* Move "croptest" to something like "crop-archive"
* Investigate what the function apps in "cropapptest" do, and whether they belong in their own resource group.
* EITHER have "cropapp" and "cropapptest" as direct clones of each other, with the only difference being the webapp pointing at either the production or test docker image, OR see if we can do something with deployment slots which would mean having the "test" and "prod" servers in the same app service plan.  In this case we should have one resource group for just the webapp and associated services, and move everything else elsewhere.

**Comment by mhauru** [comment]
There are now two deployments running, http://cropapptest.azurewebsites.net/home/index and http://cropapptest-dev.azurewebsites.net/home/index, which get new container builds on push to `main` and `develop` respectively.

**Comment by nbarlowATI** [comment]
* Moved the storage account in `croptest` into a new resource group `crop-archive`.   
 * Currently investigating whether there is any data in the postgres server in `cropapp` that is not in the equivalent db (which is actually being used) in `cropapptest`.   If not, will delete `cropapp` resource group.

**Comment by mhauru** [comment]
Did we decide what to do with the `cropmodels` VM? I think except for that, this issue is done.

**Comment by nbarlowATI** [comment]
I'm not sure we previously arrived at a decision, but we can make one now :)
Personally I think we can delete it - I don't think there's anything on it now that we would use when investigating running the models, and we can always provision a VM if we need one for something else...
But I'm open to persuasion...

**Comment by mhauru** [comment]
I support deleting it too.

By unanimous verdict, to the gallows it is for `cropmodels`.

**Comment by mhauru** [comment]
It has been done.
