### ISSUE TITLE
Incorporating data from GROW app

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/CROP#243]
We have access to the growapp db.
List of questions/ things to clarify:
* "crop" table - are `propagation_period` and `grow_period` in days?
* "crop" table - what is `is_pre_harvest`?
* "tray_type" - what are "size" and "amount_per_bench", "display_order" ?
* is "user" referring to a farm user?

"batch" looks useful - has current status of everything in farm?  has references to events, presumably from "batch_event"?  has "bench_id" - can we use "location_id" instead? 

First thinking about what data we keep - 

Batch
------
id (ours - PK)
growapp_id (theirs)
tray_size
number_of_trays
crop_id : foreignkey to CropType table
(tray_type_id) - is this pre-determined by location - old/new farm

BatchEvent
------------
id
event_type
date
batch_id
(user) - do we want to keep this?
(was_manual) - do we want to keep this?
current_location - foreignkey to Location table.
next_action_days

CropType
----------
id
name
seed_density
propagation_period
grow_period
is_pre_harvest

Harvest
--------
id
batch_event_id
crop_yield
waste_disease
waste_defect
over_production

 - [x] Add schema (classes in `structure.py`)
 - [x] Write Azure function to ingress
 - [x] Write api endpoints (`routes.py`) to access data
 - [x] Example plots / analysis (Jupyter?)

**Comment by nbarlowATI** [comment]
Also, how often do we want our function app that imports this data to run?   Twice per day?

**Comment by mhauru** [comment]
Since the backend part of this seems to be done, I'll close. See discussion for front end side here: https://github.com/alan-turing-institute/CROP/issues/284
