### ISSUE TITLE
Include weather forecast

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/CROP#257]
openweathermap can give us weather forecast, which we should store in a separate table from weather history.
How far ahead should we look?   How should we supersede older forecasts with newer, closer-to-the-date forecasts? 
Suggest just have columns for date-of-forecast and date-being-forecast, and always take the latest date-of-forecast entry for a given date-being-forecast.

**Comment by mhauru** [comment]
Could also consider not superseding in any way, just storing all of it. Assuming we don't get weather data very often. If we do get it very often, then maybe only keep one value for every date-of-forecast and datetime-being-forecast.

I guess the question is, what are all the plausible use cases for historical weather predictions. Training some models we might implement in the future, something else?

**Comment by nbarlowATI** [comment]
Laying out a possible approach for this, for the benefit of @dsj976 :  
1) Checkout the `develop` branch, and make a new branch off it to work in:
```
#(from main CROP directory)
git checkout develop
git pull
git checkout -b feature/weather-forecast
```
2) Edit the file `__app__/crop/structure.py`, adding a new SQLAlchemy class (corresponding to a database table) for WeatherForecasts.
3) Make a new file `__app__/crop/ingress_weather_forecast.py` following the rough template of `ingress_weather.py`, but getting forecast rather than historical data.   Note that the `ingress_weather.py` methodology is to get data from the API, then look at the timestamps of data already in the DB, and only add new data.   It is not clear whether or not that is also the best approach for forecast data (since tomorrow's forecast of Friday's weather is going to be better than today's forecast).    To test these functions as you write them, you will need the openweathermap API key, which should be in your environment after having sourced `.secrets/crop.sh`.
4) Make a new directory `__app__/weather_forecast_func` following the template of `__app__/weather_func` - this is for the Azure function, and will call the code in the `ingress_weather_forecast.py` that you just wrote.
5) Commit and push all this code to the repo, and make a Pull Request for this branch to go into `develop` (ask us if any of this is not obvious! :) ) with me and/or Markus as a reviewer.

Before doing even steps `2)`  and `3)` though, it would probably be good to investigate what is available, and how to get it, from the openweathermap API (documentation at https://openweathermap.org/api).
