### ISSUE TITLE
3D web interface

### ISSUE THREAD

**Issue by entopia** [alan-turing-institute/CROP#28]
- [x] fix model
- [x] choosing UX
- [x] choose framework connecting to db
- [ ] make sure all the components are communicating (UX, framework, db)
- [ ] generate object based on db locations-sensors
- [ ] click on object (raytracing)
- [ ] put out information in label
- [ ] panel of information (with some random text)

-

**Comment by tomaslaz** [comment]
Closing as it is no longer relevant
