### ISSUE TITLE
Create interactive GES model

### ISSUE THREAD

**Issue by rmward61** [alan-turing-institute/CROP#327]
The GES model is intended to be run interactively with the user able to change the scenario and see the impact on the farm environmental conditions.  This could be achieved by including 'sliders' for parameters such as ventilation rate, lighting switch-on time, lighting duration, number of dehumidifiers etc.  This could also have a slider for current lighting percentage as at present the number of lights switched on is hard-wired in (and currently incorrect).

Assigned everyone to this task as we need to discuss how this will be achieved :)

**Comment by nbarlowATI** [comment]
Some notes from discussions on 20/1/23:
* Introduce new "scenario" table to the DB, with columns for the different variables we might want to change.
* The "measure" table would have an additional column "scenario_id", and we would have "mean temperature" and "mean humidity" measures (i.e. rows) for every new scenario we add.
* Timingwise, it seems feasible to be able to run a few hundred scenarios in the Azure function run, and store the results.
* Initial suggestion for what scenarios to add:
  - ventilation_rate: 2,4,6,8,10
  - num_dehumidifiers: 0, 1, 2
  - lighting_shift: -6,-3, 0, 3, 6
  - lighting_on_duration: 12, 14, 16, 18, 20 
 Taking Cartesian product of these gives a total of 5x3x5x5 = 375 combinations.
