### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/CROP#328]
I just realised CROP isn't using SSL (aka httpS). Good practice to do so, especially on page with loads of javascript and logins and all.

**Comment by nbarlowATI** [comment]
Ticked the "https only" box for both cropapp and cropapptest App Services in the Azure Portal.   (I think that's all we needed to do, right?)

**Comment by mhauru** [comment]
That seems to have done it, thanks.
