### ISSUE TITLE
Automate cloud deployment

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/CROP#333]
Fix the old shell scripts, or start using something like Pulumi or Terraform

**Comment by nbarlowATI** [comment]
Planning (17/1/23), thoughts:
* Try Pulumi, start simple, create DB and then webserver, see if we hit any hurdles.
* If we do find something difficult, investigate whether it might be easier in Terraform.
* Probably Function Apps might be more challenging - build up to them...
