### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by tomaslaz** [alan-turing-institute/CROP#67]
Model returns errors when is used in the development webapp: 

https://cropapptest.azurewebsites.net/

**Comment by entopia** [comment]
Hi Tomas, what errors does it return?

**Comment by tomaslaz** [comment]
Hi Flora,

Right side: seems to be constant text
Left side: 404 not found

P.s. I think your credentials should work if you would like to login and check it on the live version.

**Comment by tomaslaz** [comment]
Fixed.
