### ISSUE TITLE
DB progress

### ISSUE THREAD

**Issue by entopia** [alan-turing-institute/CROP#8]
- In the bulk mapping function, it adds data instead of replacing if something changes in the csv. Need to check how it does the recordings. 

Relationships: 
https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#one-to-many

If table doesnt exist, sqlalchemy cannot create it if it contains some relationship ? whyy?  <-- SOlVED. 
need to ccheck if tables exist, if not create them first, then make relationships. 

*Base.metadata.create_all(engine)#<---** this one creates all tables, how can i create just one?? #subclass?

**Comment by tomaslaz** [comment]
Not relevant anymore.
